language: java
jdk:
  - oraclejdk8

dist: trusty
sudo: required

install: true

jobs:
  include:
  - stage: support-build-oraclejdk8
    script: bash scripts/build.sh
  - stage: test-sample-bank-service-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-bank-service/pom.xml verify
  - stage: test-sample-combined-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-combined/pom.xml verify
  - stage: test-sample-jms-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-jms/pom.xml verify
  - stage: test-sample-jms-fax-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-jms-fax/pom.xml verify
  - stage: test-sample-mail-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-mail/pom.xml verify
  - stage: test-sample-rest-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-rest/pom.xml verify
  - stage: test-sample-ws-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-ws/pom.xml verify
  - stage: test-sample-ws-client-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-ws-client/pom.xml verify
  - stage: test-sample-wsdl-oraclejdk8
    script:
    - mvn -f simulator-samples/sample-wsdl/pom.xml verify
  - stage: lts-build-openjdk11
    jdk: opendjk11
    script:
      - mvn --batch-mode -q -Pskip-it clean install -Dembedded -Djava.version=11
  - stage: latest-build-openjdk12
    jdk: opendjk12
    script:
      - mvn --batch-mode -q -Pskip-it clean install -Dembedded -Djava.version=12

stages:
  - support-build-oraclejdk8
  - test-sample-bank-service-oraclejdk8
  - test-sample-combined-oraclejdk8
  - test-sample-jms-oraclejdk8
  - test-sample-jms-fax-oraclejdk8
  - test-sample-mail-oraclejdk8
  - test-sample-rest-oraclejdk8
  - test-sample-ws-oraclejdk8
  - test-sample-ws-client-oraclejdk8
  - test-sample-wsdl-oraclejdk8
  - lts-build-openjdk11
  - latest-build-openjdk12

cache:
  directories:
  - '$HOME/.sonar/cache'
  - '$HOME/.m2'

addons:
  sonarcloud:
    organization: "citrusframework"
    token:
      secure: "TJGwqMwihT6FU/jiExqGrL4YCJVJKKBu30bx0dHaromZ7Au4/gfKk3MgH67h3gU39lcEkDSEpZXIhimnbnpHbTqh8I4M6umQRilpkDRfsweMBiBXW+MFy+hoy4njbsD3n6NGleNRlAy2zaL7+/E/uHl5TExtplG5dAy1yIeNxv7F+n/QfDj/lewIBFFSDNTX+LEUslxs5cqSRTaAxRJMayf4mxLRN0EpjeILlGS/vaIB7ME6fCodj4L1GettBtXcjEDkKaevhl/XyFU3UFXkSTpH53lRdqMMFfB4NYG8lWquPCicv6ein+wxbDpPUVIWdHX7Xp94sUZ3QRUTgO19bRQkZFiZSrffDA19OexLvdjRkUagMGPz7iE+U0X0/tk8+qvxm6/lFt7rfZUcDCHHa8cV+PLFCR2zh3J1lCYqpABUhpRQTA8CDgQJopGk9gakKcslmwvvGtRjpCsrgGnofgzc3DJ+qLIcJKVGwDWeVSvdtiJgpFnGwbmQ2O0W1mH3S431L4vxtgKmcIhkK4CyjIzLgEt0YOo0Loqe0szVY2VhB7kfgRAsWq5l02SihpgFMoSBrdx0kdbusgXjgzJxKbv5IY2Y2xBTRATClc0Bl1yJzJsSm5wF0LdQTKkCsTPxJBCLL4AmfYlWd2wk6t7OJQ0YiqmA93cbdaYjVmrUYMY="
